import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    tutorialSidebar: [
        {type: 'autogenerated', dirName: '.'},

        {
            type: 'html', // refer this : https://docusaurus.io/docs/sidebar/items#sidebar-item-html
            value: '<hr/>',
            defaultStyle: true,
        },

        {
            type: 'category', // Ref : https://docusaurus.io/docs/sidebar/items#sidebar-item-category
            label: 'Category Example',
            items: ['nested_pages/NestedPage1'],
        },

        {
            type: 'link', // Ref : https://docusaurus.io/docs/sidebar/items#sidebar-item-link
            label: 'Youtube docusaurus tutorials',
            href: 'https://www.youtube.com/playlist?list=PLY91jl6VVD7wn8SHdWKRg3AAEKbHQYaNL',
        },

        {
            type: 'category', // Ref : https://docusaurus.io/docs/sidebar/items#sidebar-item-category
            label: 'Check category link points to internal doc with items',
            collapsed: true, // Set the category to be initially collapsed or open by default
            collapsible: true, // Set the category to be collapsible
            link: {
                type: 'doc',
                id: 'nested_pages/NestedPage1', // The link label
            },
            items: ['nested_pages/NestedPage2'],
        },

        {
            type: 'category',
            label: 'Check category link points to internal doc without items',
            link: { // Ref : https://docusaurus.io/docs/sidebar/items#category-doc-link
                type: 'doc',
                id: 'nested_pages/NestedPage1',
            },
            items: [],
        },

        {
            type: 'doc', // You can also use short form refer this : https://docusaurus.io/docs/sidebar/items#sidebar-item-doc
            id: 'nested_pages/NestedPage1',
            label: 'Check doc type',
        },

        {
            type: 'category', // Ref : https://docusaurus.io/docs/sidebar#complex-sidebars-example
            label: 'External Links',
            collapsed: true,
            collapsible: true,
            items: [{

                type: 'link',
                label: 'Youtube docusaurus tutorials',
                href: 'https://www.youtube.com/playlist?list=PLY91jl6VVD7wn8SHdWKRg3AAEKbHQYaNL',
            }],
        },
    ],

    mySidebar2: [

        {
            type: 'category', // Ref : https://docusaurus.io/docs/sidebar/items#sidebar-item-category
            label: 'Operators Example',
            items: ['operators/test'],
        },
    ]

    // But you can create a sidebar manually
    /*
    tutorialSidebar: [
      'intro',
      'hello',
      {
        type: 'category',
        label: 'Tutorial',
        items: ['tutorial-basics/create-a-document'],
      },
    ],
     */
};

export default sidebars;
